lionbi_admin:
    path: /admin/{reactRouting}
    defaults: { _controller: EarlsLionBiBundle:Admin:default, reactRouting: null }
    requirements:
        reactRouting: ".+"
    
lion_bi_rest_v1 : 
  type : rest 
  resource : "@EarlsLionBiBundle/Resources/config/routing/rest.yml"
  prefix : /api/v1