Earls\LionBiBundle\Form\Model\ReportTable:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    displayId:
      expose: true
    position:
      expose: true
    reportConfig:
      expose: true
    headers:
      expose: true
    categories:
      expose: true