lionbi_dataReport_list:
    pattern: /list
    defaults: { _controller: EarlsLionBiBundle:Data:list }
    
lionbi_dataReport_editor:
    pattern: /editor
    defaults: { _controller: EarlsLionBiBundle:Data:editor }
    
lionbi_dataReport_saveDataReport:
    pattern: /save_date_report
    defaults: { _controller: EarlsLionBiBundle:Data:DataReport }
    
lionbi_dataReport_getJsonDataReport:
    pattern: /getJsonDataReport/{id}
    defaults: { _controller: EarlsLionBiBundle:Data:getJsonDataReport }