lionbi_dataReport_list:
    path: /list
    defaults: { _controller: EarlsLionBiBundle:DataReport:list }
    
lionbi_dataReport_editor:
    path: /editor
    defaults: { _controller: EarlsLionBiBundle:DataReport:editor }
    
lionbi_dataReport_sqlEditor:
    path: /sqleditor
    defaults: { _controller: EarlsLionBiBundle:DataReport:sqlEditor }
    
lionbi_dataReport_saveDataReport:
    path: /save_date_report
    defaults: { _controller: EarlsLionBiBundle:DataReport:saveDataReport }
    
lionbi_dataReport_getJsonDataReport:
    path: /getJsonDataReport/{id}
    defaults: { _controller: EarlsLionBiBundle:DataReport:getJsonDataReport }