lionbi_report_list:
    pattern: /list
    defaults: { _controller: EarlsLionBiBundle:Report:list }
    
lionbi_report_editor:
    pattern: /editor
    defaults: { _controller: EarlsLionBiBundle:Report:editor }